server:
  port: 8101

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/customer
    username: customer-api
    password: customer-api
    driver-class-name: com.mysql.cj.jdbc.Driver

  devtools:
    remote:
      restart:
        enabled: true
    livereload:
      enabled: true
