server: 
  port: 8103

spring: 
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/saving
    username: saving-api
    password: saving-api
    driver-class-name: com.mysql.cj.jdbc.Driver

  devtools:
    remote:
      restart:
        enabled: true
    livereload:
      enabled: true
