server: 
  port: 8104
spring: 
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/vdebit
    username: vdebit-api
    password: vdebit-api
    driver-class-name: com.mysql.cj.jdbc.Driver

  devtools:
    remote:
      restart:
        enabled: true
    livereload:
      enabled: true
