server:
  port: 8102

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/account
    username: account-api
    password: account-api
    driver-class-name: com.mysql.cj.jdbc.Driver

  devtools:
    remote:
      restart:
        enabled: true
    livereload:
      enabled: true
